# 1. Tensor Manipulations & Reshaping

Task: Tensor Reshaping & Operations

In [1]:
import tensorflow as tf

In [24]:
#Creating a random tensor of shape(4,6)
tensor = tf.random.uniform(shape = (4,6),minval = 1, maxval = 20,dtype = tf.int32)
print("The random tensor is : ",'\n',tensor.numpy())

#Finding the rank and shape of the tensor using the TensorFlow functions
rank = tf.rank(tensor)
shape = tf.shape(tensor)

print("The rank of the tensor is : ",rank.numpy())
print("The shape of the tensor is : ",shape.numpy())

The random tensor is :  
 [[ 4  3  9  8 19 10]
 [18 11  3 18  1 15]
 [13  2  9  7 17  2]
 [ 4 12 10  5  1 19]]
The rank of the tensor is :  2
The shape of the tensor is :  [4 6]


In [25]:
#Reshaping the tensor into (2, ,3, 4)
reshape_tensor = tf.reshape(tensor, (2, 3, 4))

#Finding the rank and shape of the tensor after reshaping 
rank = tf.rank(reshape_tensor)
shape = tf.shape(reshape_tensor)

print("The rank of the reshape_tensor is : ",rank.numpy())
print("The shape of the reshape_tensor is : ",shape.numpy())

The rank of the reshape_tensor is :  3
The shape of the reshape_tensor is :  [2 3 4]


In [26]:
#Transposing the reshaped tensor into (3, 2, 4)
transposed_tensor = tf.transpose(reshape_tensor, perm = [1, 0, 2])

#Finding the rank and shape of the tensor after transposed
rank = tf.rank(transposed_tensor)
shape = tf.shape(transposed_tensor)

print("The rank of the transposed tensor is : ",rank.numpy())
print("The shape of the transposed tensor is : ",shape.numpy())

The rank of the transposed tensor is :  3
The shape of the transposed tensor is :  [3 2 4]


In [29]:
#Broadcasting the smaller tensor (1, 4)
smaller_tensor = tf.random.uniform(shape =(1, 4), minval = 1, maxval = 20, dtype =tf.int32)
print("The smaller tensor is : ",'\n',smaller_tensor.numpy())

#Adding the smaller tensor with the larger tensor
broadcasted_sum = transposed_tensor + smaller_tensor

print('\nThe broadcasted sum of the smaller tensor and larger tensor is : ','\n',broadcasted_sum.numpy())

The smaller tensor is :  
 [[ 4 15 18  1]]

The broadcasted sum of the smaller tensor and larger tensor is :  
 [[[ 8 18 27  9]
  [17 17 27  8]]

 [[23 25 36 12]
  [21 17 22 13]]

 [[ 7 33 19 16]
  [14 20 19 20]]]


# Explain how broadcasting works in TensorFlow

Broadcasting in TensorFlow allows you to perform element-wise operations on tensors with different shapes without having to manually duplicate data. When you add two tensors of different shapes, TensorFlow automatically expands the smaller tensor to match the shape of the larger one, making the operation possible.

How Broadcasting Works:

TensorFlow compares the dimensions of both tensors starting from the rightmost side.
Two dimensions are considered compatible if:
They are the same, or one of them is 1 (which allows TensorFlow to stretch or "broadcast" it to match the other dimension).

Example: 
In our case, we have a tensor with shape (3, 2, 4) and a smaller tensor with shape (1, 4). TensorFlow automatically expands the smaller tensor across the first two dimensions, effectively treating it as if it had the shape (3, 2, 4), without actually copying the data. This makes the addition operation seamless and efficient.